FROM node as build

WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm ci
COPY . .

RUN npm run build



# production environment
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
